### ISSUE TITLE
PYNQ-Z2 Arduino接口 i2c如何使用

### ISSUE THREAD

**Issue by wilson1117** [AIoTcompetition/SmartLiving#11]
請問BaseOverlay中 可以使用Arduino 接口的i2c嗎
如果可以 他使用的函式是什麼 謝謝

**Comment by JeffInElements** [comment]
https://pynq.readthedocs.io/en/v2.6.1/pynq_libraries/arduino.html
https://pynq.readthedocs.io/en/v2.6.1/pynq_package/pynq.lib/pynq.lib.arduino.html#pynq-lib-arduino
![14685f9b9997bf4e8a6fd33ff1db5b1](https://user-images.githubusercontent.com/84759322/124528424-b4ef8e80-de3a-11eb-9d5d-e2be89a5f098.png)
有 Grove这些library用I2C
