### ISSUE TITLE
PYNQ-Z2無法開機

### ISSUE THREAD

**Issue by yz380270834** [AIoTcompetition/SmartLiving#3]
大家好，
請問有人的PYNQ-Z2可以正常開機使用嗎?
我的板子只有成功亮起電源燈
![S__4014083](https://user-images.githubusercontent.com/69102871/119112600-d2b58f80-ba56-11eb-96e5-630398b47a5d.jpg)
我的電腦也抓不到他的USB
![1621587487001](https://user-images.githubusercontent.com/69102871/119112706-f4167b80-ba56-11eb-8c54-378ec49b2411.jpg)
確定跳線有設置在SD的位置
SD卡也有裝載官網的映像檔
![S__4014086](https://user-images.githubusercontent.com/69102871/119112887-22945680-ba57-11eb-8f0a-a5e3b73b9e40.jpg)

**Comment by JeffInElements** [comment]
solutions:
1. 換一條 USB cable。
2. 換一張sd卡燒錄。
3. 燒好的sd卡放到別的版子確認是否可用。
4. 用別人燒好可以正常開機的sd卡來試這張版子。

**Comment by yz380270834** [comment]
![S__4096004](https://user-images.githubusercontent.com/69102871/119448562-1adcf680-bd64-11eb-8681-a9f1bafa9f34.jpg)
換另外一條線 使用原廠提供的SD卡問題一樣
換另外一條線 使用另外一張32G SD後一顆綠燈都沒有了
![S__4096007](https://user-images.githubusercontent.com/69102871/119448842-74ddbc00-bd64-11eb-99a8-1daea480f6f1.jpg)

**Comment by kevintseng01** [comment]
Hi, 經FAE判斷，需拿回來檢測，已經先派發另一片給您摟

**Comment by yz380270834** [comment]
已解決 謝謝
