### ISSUE TITLE
教學影片的jupyter檔案

### ISSUE THREAD

**Issue by wilson1117** [AIoTcompetition/SmartLiving#9]
請問再ADI_Smoke Detection x PYNQ的教學影片中，jupyter的檔案是否能提供，謝謝

**Comment by YuTecHealth** [comment]
您好，

請參考此壓縮包 [Smoke_python_code_ex.zip](https://github.com/AIoTcompetition/SmartLiving/files/6666917/Smoke_python_code_ex.zip)，檔案內容包含指令流程摘要以及對應的.ipynb檔案，再麻煩嘗試看看囉!
